#title: AVERtek # your name photo (or website title) here
logo1: "/images/avenidaPDlogo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b><h3 style="text-align: center;" markdown="1"><b>SECRET OF FUN LIVING</h3></b> 
  <b><h4 style="text-align: center;" markdown="1"><b>POWERFUL BREADCRUMB MARKETING TELLS STORIES</b></h4>
  <h5 style="text-align: center;" markdown="2"> 3D image allows viewers to rotate, spin & zoom to scale the images</h5>
  <br> 
  <b><h3 style="text-align: center;" markdown="1"><b>SHOW IMAGES/EVENTS THAT ROMANCE COMMUNITY LIVING</b></h3>
  <h5 style="text-align: center;" markdown="2"> Augmented Reality (AR) transports your story into the Prospect's memory!</h5>
  <br>
  <b><h3 style="text-align: center;" markdown="1"><u><a href="https://avertek.net/xr-now-apartments">LINK EXCITING STORIES/CONTENT</u></b></h3>
  <h5 style="text-align: center;" markdown="2"> Help Prospects visualize a new lifestyle</a></h5> 
  <br>
  <a href="https://youtu.be/5YSBRmMTybU"><b><h3 style="text-align: center;" markdown="1"><u>SHARE TESTIMONIALS</u></h3></b>- Show viewers fun/friendly residents</a>
  <br>
  <a href="https://avertek.net/contact-us"><b><h3 style="text-align: center;" markdown="1"><u>EXPERIENCE "LIVING LIFE TODAY"</u></h3></b>- Take a VIP tour, Get a special gift</a> 
  <br>

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
